### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by hanspeterstalder** [rossmoody/link-roamer#1]
It would be nice if Link Roamer's functions were accessible through keyboard shortcuts. This extension would be a enrichment for blind people.

**Comment by rossmoody** [comment]
Hanspeter! How awesome of you to file this. So cool and such a great idea. Will do this today. This ticket also reminds me I need to do some voice-over runs and see how things are being read aloud.

**Comment by rossmoody** [comment]
This one went into v1.2.0! Thank you again for the suggestion. Ctrl + U is the default keybinding!
